# Generated by Django 5.0 on 2023-12-31 07:20

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

   
